import sys
print(sys.version)
print(sys.version_info)
print(sys.version_info.major)
print(sys.version_info.minor)
print(sys.version_info.micro)
print(sys.version_info.releaselevel)
print(sys.version_info.serial)
print(sys.version_info.major == 3)
print(sys.version_info.minor == 7)
print(sys.version_info.micro == 5)
print(sys.version_info.releaselevel == 'final')
print(sys.version_info.serial == 0)
print(sys.version_info.major == 3 and sys.version_info.minor == 7)
print(sys.version_info.major == 3 and sys.version_info.minor == 7 and sys.version_info.micro == 5)
print(sys.version_info.major == 3 and sys.version_info.minor == 7 and sys.version_info.micro == 5 and sys.version_info.releaselevel == 'final')
print(sys.version_info.major == 3 and sys.version_info.minor == 7 and sys.version_info.micro == 5 and sys.version_info.releaselevel == 'final' and sys.version_info.serial == 0)